# Generated by Django 2.1.7 on 2020-11-12 08:21

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_gender', models.CharField(max_length=10, null=True)),
                ('user_com_type', models.CharField(max_length=20, null=True)),
                ('user_com', models.CharField(max_length=30, null=True)),
                ('user_birthday', models.DateTimeField(null=True)),
                ('user_show_message', models.BooleanField(null=True)),
                ('user_show_likes', models.BooleanField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('album_name', models.CharField(max_length=50)),
                ('album_date', models.DateTimeField(null=True)),
                ('album_singer_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollectInList',
            fields=[
                ('collect_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('singer_id', models.AutoField(primary_key=True, serialize=False)),
                ('singer_name', models.CharField(max_length=20)),
                ('singer_gender', models.BooleanField(null=True)),
                ('singer_msg', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=50)),
                ('song_likes', models.IntegerField(null=True)),
                ('song_album_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_album', to='musicBase.Album')),
            ],
        ),
        migrations.CreateModel(
            name='SongComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_msg', models.TextField(null=True)),
                ('comment_song_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_song', to='musicBase.Song')),
                ('comment_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SongLikes',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('like_song_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_song', to='musicBase.Song')),
                ('like_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SongList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_name', models.CharField(max_length=50, null=True)),
                ('list_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='collectinlist',
            name='collect_list_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collect_list', to='musicBase.SongList'),
        ),
        migrations.AddField(
            model_name='collectinlist',
            name='collect_song_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collect_song', to='musicBase.Song'),
        ),
    ]
