# Generated by Django 2.1.7 on 2020-11-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicBase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='singer_gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
