# Generated by Django 2.1.7 on 2020-10-16 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicBase', '0002_auto_20201016_1112'),
    ]

    operations = [
    ]
