# Generated by Django 2.1.7 on 2020-11-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicBase', '0002_auto_20201114_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='singer_gender',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
