# Generated by Django 2.1.7 on 2020-11-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicBase', '0003_auto_20201115_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='singer_gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
