# Generated by Django 2.1.7 on 2020-10-19 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicBase', '0003_auto_20201016_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='id',
        ),
        migrations.RemoveField(
            model_name='singer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='album',
            name='album_data',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_singer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='singer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='singer',
            name='singer_msg',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_album_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_produce',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_singer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_singer_id', to='musicBase.Singer'),
        ),
        migrations.AlterField(
            model_name='songcomment',
            name='comment_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='songcomment',
            name='comment_msg',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='songcomment',
            name='comment_song_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='songlikes',
            name='like_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='songlikes',
            name='like_song_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
