# Generated by Django 2.1.7 on 2020-11-15 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicBase', '0004_auto_20201115_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_singer_id',
            new_name='singer_id',
        ),
    ]
