# Generated by Django 2.1.7 on 2020-10-19 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicBase', '0004_auto_20201019_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songlikes',
            name='like_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_user_id', to='musicBase.User'),
        ),
    ]
