# Generated by Django 2.1.7 on 2020-10-19 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicBase', '0005_auto_20201019_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songcomment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='songlikes',
            name='id',
        ),
        migrations.AlterField(
            model_name='song',
            name='song_album_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_album', to='musicBase.Album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_singer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_singer', to='musicBase.Singer'),
        ),
        migrations.AlterField(
            model_name='songcomment',
            name='comment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='songcomment',
            name='comment_msg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_song', to='musicBase.Song'),
        ),
        migrations.AlterField(
            model_name='songlikes',
            name='like_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='songlikes',
            name='like_song_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_song', to='musicBase.Song'),
        ),
        migrations.AlterField(
            model_name='songlikes',
            name='like_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to='musicBase.User'),
        ),
    ]
