# Generated by Django 2.1.7 on 2020-11-15 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicBase', '0005_auto_20201115_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_album_id',
            new_name='album_id',
        ),
    ]
