# Generated by Django 2.1.7 on 2020-10-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicBase', '0006_auto_20201019_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_data',
            new_name='album_date',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_singer_id',
        ),
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
