# Generated by Django 2.1.7 on 2020-11-15 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicBase', '0006_auto_20201115_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='singer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_singer', to='musicBase.Singer'),
        ),
    ]
