# Generated by Django 2.1.7 on 2020-11-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicBase', '0007_auto_20201115_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_com_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_show_likes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_show_message',
        ),
    ]
