# Generated by Django 2.1.7 on 2020-10-29 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicBase', '0008_auto_20201029_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectInList',
            fields=[
                ('collect_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SongList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_name', models.CharField(max_length=50, null=True)),
                ('list_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_user', to='musicBase.User')),
            ],
        ),
        migrations.AddField(
            model_name='collectinlist',
            name='collect_list_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collect_list', to='musicBase.SongList'),
        ),
        migrations.AddField(
            model_name='collectinlist',
            name='collect_song_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collect_song', to='musicBase.Song'),
        ),
    ]
